version: 2.1

orbs:
  python: circleci/python@2

jobs:
  test-python:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: pytest --junitxml=junit.xml
      - store_test_results:
          path: junit.xml
      - store_artifacts:
          path: junit.xml
          destination: test-results

  build-package:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install Build Tools
          command: |
            pip install --upgrade pip
            pip install build
      - run:
          name: Build Python Package
          command: python -m build
      - store_artifacts:
          path: dist
          destination: artifacts

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Deploy Package
          command: echo "Deploy step placeholder. Replace this with deployment commands."

workflows:
  build-and-test:
    jobs:
      - test-python
      - build-package:
          requires:
            - test-python
    # Uncomment this section to include deployment
    # - deploy:
    #     requires:
    #       - build-package
